base_dir = "."
project_name = "libexpat"
src_globs = [
    "translated_rust/src/*.rs",
    "translated_rust/src/*/*.rs",
    "translated_rust/src/*/*/*.rs",
    "translated_rust/src/*/*/*/*.rs",
]
test_command = """
set -e
cd translated_rust
cargo build
# TODO: run the C tests
"""

[transpile]
output_dir = "translated_rust"

[[transpile.artifacts]]
name = "libexpat"
configure_cmds = [
  "mkdir build",
  "cd build && sh ../expat/configure --without-xmlwf --without-examples --without-tests",
]
build_cmds = ["make -C build"]
