[workspace]
members = [
]
[package]
name = "translated_rust"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "translated_rust"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]
[[bin]]
path = "c2rust-bin-runtests.rs"
name = "runtests"
[dependencies]
c2rust-bitfields = "0.22.1"


[profile.release]
strip = "debuginfo"